server:
  port: 8327

spring:
  application:
    name: nacos-service-consumer-seata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=UTF-8&nullNamePatternMatchesAll=true&allowMultiQueries=true
    username: root
    password: hyflearn
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: SEATA_GROUP
        namespace: seata
        cluster-name: SEATA_CLIENT_CLUSTER_REAL

order-service-name: nacos-service-provider-seata-order
store-service-name: nacos-service-provider-seata-store

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

seata:
  enabled: true
  application-id: application-id-consumer
  tx-service-group: hyf_tc_group # 一个自定义的客户端事务组
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  use-jdk-proxy: false
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  client:
    rm:
      async-commit-buffer-limit: 10000 # 异步提交缓存队列长度，二阶段提交成功，RM异步清理undo队列
      report-retry-count: 5 # 一阶段结果上报TC重试次数
      table-meta-check-enable: false # 自动刷新缓存中的表结构
      report-success-enable: false # 是否上报一阶段成功。true用于保持分支事务生命周期记录完整，false可提高不少性能
      saga-branch-register-enable: false
      saga-json-parser: fastjson
      saga-retry-persist-mode-update: false
      saga-compensate-persist-mode-update: false
      lock:
        retry-interval: 10 # 校验或占用全局锁重试间隔，单位毫秒
        retry-times: 30 # 校验或占用全局锁重试次数
        retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略，默认true，优先释放本地锁让回滚成功
    tm:
      commit-retry-count: 5 # 一阶段全局提交结果上报TC重试次数，默认1次，建议大于1
      rollback-retry-count: 5 # 一阶段全局回滚结果上报TC重试次数，默认1次，建议大于1
      default-global-transaction-timeout: 60000
      degrade-check: false # 业务侧根据连续错误数自动降级不走seata事务，也会自动恢复
      degrade-check-period: 2000 # 服务自检周期
      degrade-check-allow-times: 10 # 升降级达标阈值
    undo:
      data-validation: true # 二阶段回滚镜像校验
      log-serialization: jackson # undo序列化方式
      log-table: undo_log # 自定义undo表名
      only-care-update-columns: true
      compress:
        enable: true
        type: zip
        threshold: 64k
    load-balance:
      type: RandomLoadBalance
      virtual-nodes: 10
  service:
    vgroup-mapping:
      hyf_tc_group: SEATA_CLUSTER_REAL # TC所在注册中心的集群名称
    grouplist:
      default: 127.0.0.1:8091 # 仅注册中心为file时使用
      SEATA_CLUSTER_REAL: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false # 全局事务开关
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  # 客户端查找服务端的配置
  config:
    type: file
    file:
      name: file.conf
    consul:
      server-addr: 127.0.0.1:8500
    apollo:
      apollo-meta: http://192.168.1.204:8801
      app-id: seata-server
      namespace: application
      apollo-accesskey-secret: ""
    etcd3:
      server-addr: http://localhost:2379
    nacos:
      namespace: "seata"
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
    zk:
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username: ""
      password: ""
    custom:
      name: ""
  # 客户端查找服务端的集群节点的配置
  registry:
    type: file
    file:
      name: file.conf
    consul:
      server-addr: 127.0.0.1:8500
      acl-token: ""
    etcd3:
      server-addr: http://localhost:2379
    eureka:
      weight: 1
      service-url: http://localhost:8761/eureka
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_CLUSTER_GROUP"
      namespace: "seata"
      username: "nacos"
      password: "nacos"
    redis:
      server-addr: localhost:6379
      db: 0
      password: ""
      timeout: 0
    sofa:
      server-addr: 127.0.0.1:9603
      region: DEFAULT_ZONE
      datacenter: DefaultDataCenter
      group: SEATA_GROUP
      address-wait-time: 3000
      application: default
    zk:
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username: ""
      password: ""
    custom:
      name: ""
  log:
    exception-rate: 100 # 日志异常输入概率，百分之一，最大 10000，目前用于undo回滚失败时异常堆栈输出，回滚失败基本是脏数据